spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/likelion-eshop
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_nationalized_character_data: true
    show-sql: true