name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - demo-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'Likelion-eshop'
          environment_name: 'likelion-eshop-env'
          version_label: ${{github.run_number}}
          region: ap-northeast-3
          deployment_package: target/likelion-0.0.1-SNAPSHOT.jar